import { fetchProjectsPopular, fetchProjectsRecent } from "api";
import Head from "next/head";
import { Container } from "react-bootstrap";
import Navigation from "stories/Layout/Navigation";
import HomeMain from "sections/Home/Main";
import Logo from "stories/Logo";
import Footer from "stories/Layout/Footer";
import HomeRecent from "sections/Home/Recent";
import { FindProjectResponseDto } from "@/dto";
import { useProjectsPopular, useProjectsRecent } from "hooks";
import * as S from "./styled";

interface HomePageProps {
  projectsPopular: FindProjectResponseDto[];
  projectsRecent: FindProjectResponseDto[];
}

const Home = ({ projectsPopular, projectsRecent }: HomePageProps) => {
  const { projects: projectsPopularCached } = useProjectsPopular(projectsPopular);
  const { projects: projectsRecentCached } = useProjectsRecent(projectsRecent);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <header>
          <Logo center />
          <Navigation />
        </header>
        <S.HomeMainContainer>
          <HomeMain projects={projectsPopularCached ?? []} />
          <hr />
          <HomeRecent projects={projectsRecentCached ?? []} />
        </S.HomeMainContainer>

        <Footer />
      </Container>
    </>
  );
};

export async function getServerSideProps() {
  const projectsPopular = await fetchProjectsPopular();
  const projectsRecent = await fetchProjectsRecent();

  return {
    props: { projectsPopular, projectsRecent },
  };
}

export default Home;
