import { fetchProjects } from "api";
import Head from "next/head";
import { Container } from "react-bootstrap";
import Navigation from "stories/Navigation/Navigation";
import { Project } from "@/entities/projects";
import HomeMain from "sections/Home/Main";
import Logo from "stories/Logo";
import Footer from "stories/Navigation/Footer";
import HomeRecent from "sections/Home/Recent";
import * as S from "./styled";

interface HomePageProps {
  projects: Project[];
}

const Home = ({ projects }: HomePageProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <header>
          <Logo center />
          <Navigation />
        </header>
        <S.HomeMainContainer>
          <HomeMain projects={projects} />
          <hr />
          <HomeRecent projects={projects} />
        </S.HomeMainContainer>

        <Footer />
      </Container>
    </>
  );
};

export async function getServerSideProps() {
  const projects = await fetchProjects();

  return {
    props: { projects },
  };
}

export default Home;
